[build-system]
requires = ["setuptools>=77", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "arches-id-generator"
version = "0.1.0"
description = "Sequential number id generator widget for Arches"
readme = "README.md"
requires-python = ">=3.10"
license = "AGPL-3.0-or-later"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Django",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
]
dependencies = ["arches>=7.6.0", "uuid-extensions>=0.1.4"]

[project.urls]
Repository = "https://github.com/flaxandteal/arches-id-generator"

[tool.setuptools.packages.find]
include = ["arches_id_generator*"]

[dependency-groups]
dev = ["pytest", "pytest-django"]

[tool.setuptools.package-data]
arches_id_generator = [
    "templates/**/*",
    "media/**/*",
    "widgets/*.json",
]
